function processed_logs = importProcessedLogList(filename)
%IMPORTFILE Import data from a text file
%  PROCESSEDLOGSS = importProcessedLogList(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as a table.
%
%  PROCESSEDXBDS = importProcessedLogList(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  PROCESSEDXBDS = importProcessedXbdList("/Data/gfi/projects/slocum/data/real_time/202109_sl_odin_bjerknes_baffins/202109_sl_odin_bjerknes_baffins_processed_xbds.dat", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-Oct-2021 15:28:52

%% Set up the Import Options and import the data
% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";
opts = detectImportOptions(filename);

% Make Variable type change here
[a, b] = ismember('segment_num', opts.VariableNames);
if a
    opts.VariableTypes{b} = 'char';
end

% Specify file level properties
%opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties 
% NOTE LogFileNames IS OFTEN MISSING!!
opts = setvaropts(opts, ["LogFileNames","mission_name", "segment_name", "segment_num", "vehicle_name", "device_str", "abort_str"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["because", "mission_name", "segment_name", "segment_num", "vehicle_name", "device_str", "abort_str"], "EmptyFieldRule", "auto");

% Import the data
processed_logs = readtable(filename, opts, 'ReadRowNames',true);
processed_logs = removevars(processed_logs,{'LogFileNames'});
% Set the dimensions to this values, essential when writing to text file,
% this will be name of column
processed_logs.Properties.DimensionNames{1}='LogFileNames';
end