function processedXbds = importProcessedXbdList(filename)
%IMPORTFILE Import data from a text file
%  PROCESSEDXBDS = importProcessedXbdList(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as a table.
%
%  PROCESSEDXBDS = importProcessedXbdList(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  PROCESSEDXBDS = importProcessedXbdList("/Data/gfi/projects/slocum/data/real_time/202109_sl_odin_bjerknes_baffins/202109_sl_odin_bjerknes_baffins_processed_xbds.dat", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-Oct-2021 15:28:52


%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Row", "segment", "dos_name", "ext", "dba_name", "file_start", "mission_name", "filesize", "lines", "dba", "dat", "plot_file"];
opts.VariableTypes = ["string", "string", "string", "categorical", "string", "string", "string", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Set the first column to the rownames
opts.RowNamesColumn = 1;

% Specify variable properties
opts = setvaropts(opts, ["segment", "dos_name", "dba_name", "file_start", "mission_name"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["segment", "dos_name", "ext", "dba_name", "file_start", "mission_name"], "EmptyFieldRule", "auto");

% Import the data
processedXbds = readtable(filename, opts,'ReadRowNames',true);
processedXbds.Row = [];

end